package libreta;

import Metodos.Metodos;
import java.io.File;
import java.util.Date;

/**
 *
 * @author 
 */
public class IngresoDatos extends javax.swing.JPanel {

    /**
     * Creates new form LibretaCalificaciones
     */
    public IngresoDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtModalidad = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtB1 = new javax.swing.JTextField();
        btnAgregarComponente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEstudiante = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNivelAcademinco = new javax.swing.JTextField();
        txtPeriodo = new javax.swing.JTextField();
        txtTitulacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtB2 = new javax.swing.JTextField();
        lblTB = new javax.swing.JLabel();
        txtS1 = new javax.swing.JTextField();
        txtS2 = new javax.swing.JTextField();
        lblFS = new javax.swing.JLabel();
        txtA1 = new javax.swing.JTextField();
        txtA2 = new javax.swing.JTextField();
        lblFA = new javax.swing.JLabel();
        lblAcreditacion = new javax.swing.JLabel();
        lblAFA = new javax.swing.JLabel();
        lblPromo = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Estudiante");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Identificacion");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Componente"); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtModalidad.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txtNombreMateria.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtNombreMateria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nota");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtB1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtB1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAgregarComponente.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnAgregarComponente.setText("Agregar Componente Educativo");
        btnAgregarComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComponenteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setText("Modalidad");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEstudiante.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar Datos");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setText("Titulacion");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setText("Periodo Academico");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel8.setText("Nivel Academico");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtNivelAcademinco.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txtPeriodo.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txtTitulacion.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BIM1");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BIM2");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TOTAL");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SUP1");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SUP2");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("FINAL");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ACREDITACION");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ASISTENCIA");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ASIS1");
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ASIS2");
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("FINAL");
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ACREDITACION");
        jLabel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("PROMOCION");
        jLabel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Educativo"); // NOI18N
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtIdentificacion.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txtB2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtB2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtB2KeyPressed(evt);
            }
        });

        lblTB.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtS1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtS1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtS1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtS1KeyPressed(evt);
            }
        });

        txtS2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtS2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtS2KeyPressed(evt);
            }
        });

        lblFS.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblFS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtA1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtA1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtA2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtA2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtA2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtA2KeyPressed(evt);
            }
        });

        lblFA.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblFA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblAcreditacion.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblAcreditacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcreditacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblAFA.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblAFA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAFA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblPromo.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblPromo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblMensaje.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstudiante)
                            .addComponent(txtModalidad)
                            .addComponent(txtNivelAcademinco)
                            .addComponent(txtPeriodo)
                            .addComponent(txtTitulacion)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreMateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtB1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtB2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtS1)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtS2)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAcreditacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtA2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(lblAFA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarComponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNivelAcademinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTitulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAcreditacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarComponente)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAFA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtB2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtB2KeyPressed
        if (evt.getKeyCode() == 10) {
            Integer to = Integer.valueOf(txtB1.getText()) + Integer.valueOf(txtB2.getText());
            if (to >= 28 && to <= 40) {
                lblTB.setText(String.valueOf(to));
                lblFS.setText(String.valueOf(to));
                lblAcreditacion.setText("Aprobado");
            } else if (to < 28 && to > 0) {
                lblTB.setText(String.valueOf(to));
            } else {
                lblMensaje.setText("Los valore ingresados estan fuera del rango deseado");
            }
        }
    }//GEN-LAST:event_txtB2KeyPressed

    private void txtS2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtS2KeyPressed
        if (evt.getKeyCode() == 10) {
            if (txtS1.getText().equals("")) {
                Integer to = Integer.valueOf(txtB1.getText()) + Integer.valueOf(txtS2.getText());
                if (to >= 28 && to <= 40) {
                    lblFS.setText(String.valueOf(to));
                    lblAcreditacion.setText("Aprobado");
                } else if (to < 28 && to > 0) {
                    lblFS.setText(String.valueOf(to));
                    lblAcreditacion.setText("Reprobado");
                } else {
                    txtS1.setText("");
                    lblFS.setText("");
                    lblAcreditacion.setText("");
                    lblMensaje.setText("Los valore ingresados estan fuera del rango deseado");
                }
            } else {
                Integer to = Integer.valueOf(txtS1.getText()) + Integer.valueOf(txtS2.getText());
                if (to >= 28 && to <= 40) {
                    lblFS.setText(String.valueOf(to));
                    lblAcreditacion.setText("Aprobado");
                } else if (to < 28 && to > 0) {
                    lblFS.setText(String.valueOf(to));
                    lblAcreditacion.setText("Reprobado");
                } else {
                    txtS1.setText("");
                    lblFS.setText("");
                    lblAcreditacion.setText("");
                    lblMensaje.setText("Los valore ingresados estan fuera del rango deseado");
                }
            }
        }
    }//GEN-LAST:event_txtS2KeyPressed

    private void txtA2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtA2KeyPressed
        if (evt.getKeyCode() == 10) {
            Integer aFinal = Integer.valueOf(txtA1.getText()) + Integer.valueOf(txtA2.getText());
            lblFA.setText(String.valueOf(aFinal));
            if (Integer.valueOf(lblFA.getText()) >= 28 && Integer.valueOf(lblFA.getText()) <= 40) {
                lblAFA.setText("Aprobado");
            } else if (Integer.valueOf(lblFA.getText()) < 28 && Integer.valueOf(lblFA.getText()) > 0) {
                lblAFA.setText("Reprobado");
            } else {
                txtA1.setText("");
                txtA2.setText("");
                lblFA.setText("");
                lblMensaje.setText("Los valore ingresados estan fuera del rango deseado");
            }
            if (lblAFA.getText().equals("Aprobado") && lblAcreditacion.getText().equals("Aprobado")) {
                lblPromo.setText("Aprobado");
            } else if (lblAFA.getText().equals("Aprobado") && lblAcreditacion.getText().equals("Reprobado")){
                lblPromo.setText("Reprobado");
            }else if (lblAFA.getText().equals("Reprobado") && lblAcreditacion.getText().equals("Aprobado")){
                lblPromo.setText("Reprobado");
            }else if (lblAFA.getText().equals("Reprobado") && lblAcreditacion.getText().equals("Reprobado")){
                lblPromo.setText("Reprobado");
            }
        }
    }//GEN-LAST:event_txtA2KeyPressed

    private void btnAgregarComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComponenteActionPerformed
        GuardarComponenteEducativo();
    }//GEN-LAST:event_btnAgregarComponenteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtNombreMateria.equals("")) {
            GuardarComponenteEducativo();
        }
        GuardarEstudiante();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtS1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtS1KeyPressed
        if (evt.getKeyCode() == 10) {
            Integer to = Integer.valueOf(txtB2.getText()) + Integer.valueOf(txtS1.getText());
            if (to >= 28 && to <= 40) {
                lblFS.setText(String.valueOf(to));
                lblAcreditacion.setText("Aprobado");
            } else if (to < 28 && to > 0) {
                lblFS.setText(String.valueOf(to));
                lblAcreditacion.setText("Reprobado");
            } else {
                txtS1.setText("");
                lblFS.setText("");
                lblAcreditacion.setText("");
                lblMensaje.setText("Los valore ingresados estan fuera del rango deseado");
            }
        }
    }//GEN-LAST:event_txtS1KeyPressed

    public void GuardarComponenteEducativo() {
        String sFichero = "ComponenteEducativo.xml";
        File fichero = new File(sFichero);

        if (fichero.exists()) {
            String cedula = txtIdentificacion.getText();
            String nombreMa = txtNombreMateria.getText();
            String bim1 = txtB1.getText();
            String bim2 = txtB2.getText();
            String total = lblTB.getText();
            String sup1 = txtS1.getText();
            String sup2 = txtS2.getText();
            String nFinal = lblFS.getText();
            String acreditacion = lblAcreditacion.getText();
            String asis1 = txtA1.getText();
            String asis2 = txtA2.getText();
            String aFinal = lblFA.getText();
            String acreditacionA = lblAFA.getText();
            String promocion = lblPromo.getText();
            Metodos opera = new Metodos();
            opera.agregarNodoComponente(cedula, nombreMa, bim1, bim2, total, sup1, sup2, nFinal, acreditacion,
                    asis1, asis2, aFinal, acreditacionA, promocion);
        } else {
            String cedula = txtIdentificacion.getText();
            String nombreMa = txtNombreMateria.getText();
            String bim1 = txtB1.getText();
            String bim2 = txtB2.getText();
            String total = lblTB.getText();
            String sup1 = txtS1.getText();
            String sup2 = txtS2.getText();
            String nFinal = lblFS.getText();
            String acreditacion = lblAcreditacion.getText();
            String asis1 = txtA1.getText();
            String asis2 = txtA2.getText();
            String aFinal = lblFA.getText();
            String acreditacionA = lblAFA.getText();
            String promocion = lblPromo.getText();
            Metodos opera = new Metodos();
            opera.crearXmlComponente(cedula, nombreMa, bim1, bim2, total, sup1, sup2, nFinal, acreditacion,
                    asis1, asis2, aFinal, acreditacionA, promocion);
        }
        txtNombreMateria.setText("");
        txtB1.setText("");
        txtB2.setText("");
        lblTB.setText("");
        txtS1.setText("");
        txtS2.setText("");
        lblFS.setText("");
        lblAcreditacion.setText("");
        txtA1.setText("");
        txtA2.setText("");
        lblFA.setText("");
        lblAFA.setText("");
        lblPromo.setText("");

    }

    public void GuardarEstudiante() {
        String sFichero = "Estudiante.xml";
        File fichero = new File(sFichero);

        if (fichero.exists()) {
            String cedula = txtIdentificacion.getText();
            String estudiante = txtEstudiante.getText();
            String modalidad = txtModalidad.getText();
            String nivel = txtNivelAcademinco.getText();
            String periodo = txtPeriodo.getText();
            String titulacion = txtTitulacion.getText();

            Metodos opera = new Metodos();
            opera.agregarNodoEstudiante(estudiante, cedula, modalidad, nivel, periodo, titulacion);
        } else {
            String cedula = txtIdentificacion.getText();
            String estudiante = txtEstudiante.getText();
            String modalidad = txtModalidad.getText();
            String nivel = txtNivelAcademinco.getText();
            String periodo = txtPeriodo.getText();
            String titulacion = txtTitulacion.getText();

            Metodos opera = new Metodos();
            opera.crearXmlEstudiante(estudiante, cedula, modalidad, nivel, periodo, titulacion);
        }
        txtEstudiante.setText("");
        txtIdentificacion.setText("");
        txtModalidad.setText("");
        txtNivelAcademinco.setText("");
        txtPeriodo.setText("");
        txtTitulacion.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarComponente;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAFA;
    private javax.swing.JLabel lblAcreditacion;
    private javax.swing.JLabel lblFA;
    private javax.swing.JLabel lblFS;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPromo;
    private javax.swing.JLabel lblTB;
    private javax.swing.JTextField txtA1;
    private javax.swing.JTextField txtA2;
    private javax.swing.JTextField txtB1;
    private javax.swing.JTextField txtB2;
    private javax.swing.JTextField txtEstudiante;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtModalidad;
    private javax.swing.JTextField txtNivelAcademinco;
    private javax.swing.JTextField txtNombreMateria;
    private javax.swing.JTextField txtPeriodo;
    private javax.swing.JTextField txtS1;
    private javax.swing.JTextField txtS2;
    private javax.swing.JTextField txtTitulacion;
    // End of variables declaration//GEN-END:variables
}
